---

- name: Provisioning skillsprofile
  hosts: all
  become: true
  vars_files:
    - vars/main.yml

  roles:
    - ubuntu-apt
    - create-www-data-user
    - ubuntu-php
    - composer
    - ubuntu-symfony-nginx
    - ubuntu-postgresql

- name: Vagrant provisioning
  hosts: vagrant
  sudo: yes
  gather_facts: true
  roles:
   - ubuntu-xdebug
